services:
  prometheus:
    image: docker.io/prom/prometheus:latest
    container_name: prometheus_server
    ports:
      - "9090:9090"
    networks:
      - monitoring
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss #docker.io/grafana/grafana:9.5.15  # Versão estável
    container_name: grafana_server
    ports:
      - "3000:3000"
    networks:
      - monitoring
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
    - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    restart: unless-stopped

  # jaeger:
  #   image: docker.io/jaegertracing/all-in-one:1.56  # Versão específica
  #   container_name: jaeger_server
  #   ports:
  #     - "16686:16686"
  #     - "14268:14268"
  #     - "14250:14250"
  #   networks:
  #     - monitoring
  #   environment:
  #     - COLLECTOR_OTLP_ENABLED=true
  #   restart: unless-stopped
  
  tempo:
    image: grafana/tempo:2.5.0
    container_name: tempo_server
    ports:
      - "3200:3200"
      - "9095:9095"
    networks:
      - monitoring
    command: 
      - "-config.file=/etc/tempo.yaml"
    volumes:
      - ./tempo-config.yml:/etc/tempo.yaml:ro
      - tempo_data:/tmp/tempo
    restart: unless-stopped

  loki:
    image: grafana/loki:3.1.0                      # ✅ NOVA linha - adicionar serviço Loki
    container_name: loki_server
    ports:
      - "3100:3100"
    networks:
      - monitoring
    volumes:
      - ./loki-config-v3.yml:/etc/loki/local-config.yml
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yml
    restart: unless-stopped             # ✅ MUDA para latest

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.102.0 #docker.io/otel/opentelemetry-collector:0.96.0  # Versão compatível
    container_name: otel-collector_server
    ports:
      - "4317:4317"
      - "4318:4318"
    networks:
      - monitoring
    volumes:
      - ./otel-config.yml:/etc/otel-collector-config.yml
    command: ["--config", "/etc/otel-collector-config.yml"]
    restart: unless-stopped

networks:
  monitoring:
    driver: bridge

volumes:
  tempo_data:
  loki_data:     