services:
  prometheus:
    image: docker.io/prom/prometheus:latest
    container_name: prometheus_server
    ports:
      - "9090:9090"
    networks:
      - monitoring
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss #docker.io/grafana/grafana:9.5.15  # Versão estável
    container_name: grafana_server
    ports:
      - "3000:3000"
    networks:
      - monitoring
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
    - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    restart: unless-stopped

  jaeger:
    image: docker.io/jaegertracing/all-in-one:1.56  # Versão específica
    container_name: jaeger_server
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
    networks:
      - monitoring
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    restart: unless-stopped

  loki:
    image:  docker.io/grafana/loki:2.9.4  # Versão que suporta volume_enabled #docker.io/grafana/loki:2.8.4  # Versão estável
    container_name: loki_server
    ports:
      - "3100:3100"
    networks:
      - monitoring
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yml
    command: -config.file=/etc/loki/local-config.yml
    restart: unless-stopped

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.102.0 #docker.io/otel/opentelemetry-collector:0.96.0  # Versão compatível
    container_name: otel-collector_server
    ports:
      - "4317:4317"
      - "4318:4318"
    networks:
      - monitoring
    volumes:
      - ./otel-config.yml:/etc/otel-collector-config.yml
    command: ["--config", "/etc/otel-collector-config.yml"]
    restart: unless-stopped

networks:
  monitoring:
    driver: bridge