server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
        http:

ingester:
  max_block_duration: 5m
  trace_idle_period: 10s

compactor:
  compaction:
    block_retention: 1h
    compacted_block_retention: 1h

querier:
  search:
    query_timeout: 30s

metrics_generator:  
  processor:  
    service_graphs:  
      dimensions: []  
      wait: 10s  
      workers: 10  
    span_metrics:  
      dimensions: []  
  storage:  
    path: /tmp/tempo/metrics

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/blocks
    pool:
      max_workers: 10
      queue_depth: 100